import dish from './sampleDish.jpg';
import three_dots from './three_dots.png';
import graph from './GRAPH.svg';
import trash from './TRASH.svg';
import rupee from './indianRupee.png';
import shrimp from './shrimp.svg';
import beer from './BEER.svg';
import chinese_noodle from './CHINESE_NOODLES.svg';
import cocktail from './cocktail.svg';
import dessert from './DESSERT.svg';
import entree from './ENTREE.svg';
import mocktail from './MOCKTAIL.svg';
import salad from './salad.svg';
import side_item from './SIDE_ITEMS.svg';
import whiskey from './WHISHKEY.svg';
import wine from './WINE.svg';
import itemSample from './itemSample.png'
import upload from './Upload_icon.svg';
import close from './CLOSE.svg';

export const dish_image = dish;
export const three_dots_image = three_dots;
export const graph_image = graph;
export const trash_image = trash;
export const rupee_image = rupee;
export const shrimp_logo = shrimp;
export const beer_logo = beer;
export const chinese_noodle_logo = chinese_noodle;
export const cocktails_logo = cocktail;
export const dessert_logo = dessert;
export const entree_logo = entree;
export const mocktail_logo = mocktail;
export const salad_logo = salad;
export const side_item_logo = side_item;
export const whiskey_logo = whiskey;
export const wine_logo = wine;
export const itemSample_logo = itemSample;
export const upload_logo = upload;
export const close_logo = close;