import totalOrders from './TOTAL_ORDERS.svg';
import onlineOrders from './ONLINE_ORDERS.svg';
import totalSales from './TOTAL_SALES.svg';
import diners from './DINERS.svg';
import employee_1 from './EMPLOYEE_RATING_STAR_1.svg';
import employee_2 from './EMPLOYEE_RATING_STAR_2.svg';
import employee_3 from './EMPLOYEE_RATING_STAR_3.svg';
import employee_4 from './EMPLOYEE_RATING_STAR_4.svg';
import employee_5 from './EMPLOYEE_RATING_STAR_5.svg';
import product_1 from './PRODUCT_RATING_STAR_1.svg';
import product_2 from './PRODUCT_RATING_STAR_2.svg';
import product_3 from './PRODUCT_RATING_STAR_3.svg';
import product_4 from './PRODUCT_RATING_STAR_4.svg';
import product_5 from './PRODUCT_RATING_STAR_5.svg';
import customer_1 from './CUSTOMER_FEEDBACK_ICON_1.svg';
import customer_2 from './CUSTOMER_FEEDBACK_ICON_2.svg';
import customer_3 from './CUSTOMER_FEEDBACK_ICON_3.svg';
import customer_4 from './CUSTOMER_FEEDBACK_ICON_4.svg';
import customer_5 from './CUSTOMER_FEEDBACK_ICON_5.svg';
import customer_6 from './CUSTOMER_FEEDBACK_ICON_6.svg';
import customer_7 from './CUSTOMER_FEEDBACK_ICON_7.svg';
import customer_8 from './CUSTOMER_FEEDBACK_ICON_8.svg';
import customer_9 from './CUSTOMER_FEEDBACK_ICON_9.svg';
import customer_10 from './CUSTOMER_FEEDBACK_ICON_10.svg';
import customer_11 from './CUSTOMER_FEEDBACK_ICON_11.svg';
import customer_12 from './CUSTOMER_FEEDBACK_ICON_12.svg';
import customer_13 from './CUSTOMER_FEEDBACK_ICON_13.svg';
import customer_14 from './CUSTOMER_FEEDBACK_ICON_14.svg';
import customer_15 from './CUSTOMER_FEEDBACK_ICON_15.svg';
import customer_16 from './CUSTOMER_FEEDBACK_ICON_16.svg';
import customer_17 from './CUSTOMER_FEEDBACK_ICON_17.svg';
import customer_18 from './CUSTOMER_FEEDBACK_ICON_18.svg';
import customer_19 from './CUSTOMER_FEEDBACK_ICON_19.svg';
import customer_20 from './CUSTOMER_FEEDBACK_ICON_20.svg';
import customer_21 from './CUSTOMER_FEEDBACK_ICON_21.svg';
import customer_22 from './CUSTOMER_FEEDBACK_ICON_22.svg';
import customer_23 from './CUSTOMER_FEEDBACK_ICON_23.svg';
import customer_24 from './CUSTOMER_FEEDBACK_ICON_24.svg';
import customer_25 from './CUSTOMER_FEEDBACK_ICON_25.svg';
import top_rank from './TOP_RANK_BADGE.svg';

export const total_orders = totalOrders;
export const online_orders = onlineOrders;
export const total_sales = totalSales;
export const diner = diners;
export const employee_rating_1 = employee_1;
export const employee_rating_2 = employee_2;
export const employee_rating_3 = employee_3;
export const employee_rating_4 = employee_4;
export const employee_rating_5 = employee_5;
export const product_rating_1 = product_1;
export const product_rating_2 = product_2;
export const product_rating_3 = product_3;
export const product_rating_4 = product_4;
export const product_rating_5 = product_5;
export const customer_feedback_1 = customer_1;
export const customer_feedback_2 = customer_2;
export const customer_feedback_3 = customer_3;
export const customer_feedback_4 = customer_4;
export const customer_feedback_5 = customer_5;
export const customer_feedback_6 = customer_6;
export const customer_feedback_7 = customer_7;
export const customer_feedback_8 = customer_8;
export const customer_feedback_9 = customer_9;
export const customer_feedback_10 = customer_10;
export const customer_feedback_11 = customer_11;
export const customer_feedback_12 = customer_12;
export const customer_feedback_13 = customer_13;
export const customer_feedback_14 = customer_14;
export const customer_feedback_15 = customer_15;
export const customer_feedback_16 = customer_16;
export const customer_feedback_17 = customer_17;
export const customer_feedback_18 = customer_18;
export const customer_feedback_19 = customer_19;
export const customer_feedback_20 = customer_20;
export const customer_feedback_21 = customer_21;
export const customer_feedback_22 = customer_22;
export const customer_feedback_23 = customer_23;
export const customer_feedback_24 = customer_24;
export const customer_feedback_25 = customer_25;
export const top_rank_badge = top_rank;