import barbecue from './barbecue.svg';
import barbecue_1 from './barbecue-1.svg';
import beer_1 from './beer-1.svg';
import beer_2 from './beer-2.svg';
import boiled_egg from './boiled-egg.svg';
import burger from './burger.svg';
import cake from './cake.svg';
import canape from './canape.svg';
import chinese from './chinese_noodles.svg';
import cocktail from './cocktail.svg';
import cocktail_1 from './cocktail-1.svg';
import coconut from './coconut.svg';
import coffee from './coffee.svg';
import corndog from './corndog.svg';
import cupcake from './cupcake.svg';
import doughnut from './doughnut.svg';
import doughnut_1 from './doughnut-1.svg';
import fish from './fish.svg';
import fish_and_chips from './fish-and-chips.svg';
import fruit from './fruit.svg';
import honey from './honey.svg';
import hot_dog from './hot-dog.svg';
import ice_cream from './ice-cream.svg';
import ice_cream_1 from './ice-cream-1.svg';
import ice_cream_2 from './ice-cream-2.svg';
import ice_cream_4 from './ice-cream-4.svg';
import ice_cream_5 from './ice-cream-5.svg';


export const barbecue_icon = barbecue;
export const barbecue_1_icon = barbecue_1;
export const beer_1_icon = beer_1;
export const beer_2_icon = beer_2;
export const boiled_egg_icon = boiled_egg;
export const burger_icon = burger;
export const cake_icon = cake;
export const canape_icon = canape;
export const chinese_icon = chinese;
export const cocktail_icon = cocktail;
export const cocktail_1_icon = cocktail_1;
export const coconut_icon = coconut;
export const coffee_icon = coffee;
export const corndog_icon = corndog;
export const cupcake_icon = cupcake;
export const doughnut_icon = doughnut;
export const doughnut_1_icon = doughnut_1;
export const fish_icon = fish;
export const fish_and_chips_icon = fish_and_chips;
export const fruit_icon = fruit;
export const honey_icon = honey;
export const hot_dog_icon = hot_dog;
export const ice_cream_icon = ice_cream;
export const ice_cream_1_icon = ice_cream_1;
export const ice_cream_2_icon = ice_cream_2;
export const ice_cream_4_icon = ice_cream_4;
export const ice_cream_5_icon = ice_cream_5;
