import accounts from './ACCOUNTS.svg';
import add from './ADD.svg';
import address from './ADDRESS_ICON.svg';
import ascending from './ASCENDING.svg';
import billAmount from './BILL_AMOUNT.svg';
import captain from './CAPTAIN.svg';
import category from './CATEGORY.svg';
import chef from './CHEF.svg';
import cogs from './COGS.svg';
import comments from './COMMENTS.svg';
import contact from './CONTACT.svg';
import dashboard from './DASHBOARD.svg';
import descending from './DESCENDING.svg';
import dineTime from './DINE_TIME.svg';
import edit from './EDIT.svg';
import expense from './EXPENSE.svg';
import food_surplus from './FOOD_SURPLUS.svg';
import fridge from './FRIDGE.svg';
import guest from './GUEST.svg';
import handBurger from './HANDBURGER.svg';
import heart from './HEART.svg';
import inventoryItems from './INVENTORY_ITEMS.svg';
import key from './KEY.svg';
import lock from './LOCK.svg';
import measurement from './MEASUREMENT.svg';
import menuItems from './MENU_ITEMS.svg';
import mop from './MOP.svg';
import mail from './MAIL.svg';
import name from './NAME.svg';
import order from './ORDER.svg';
import price from './PRICE.svg';
import quantityPerTable from './QUANTITY_PER_TABLE.svg';
import quotation from './QUOTATION.svg';
import rating from './RATING.svg';
import rating2 from './RATING2.svg';
import rating3 from './RATING3.svg';
import remove from './REMOVE.svg';
import restaurantIcon from './RESTAURANT_ICON.svg';
import revenue from './REVENUE.svg';
import sendIcon from './SEND_ICON.svg';
import sendOrder from './SEND_ORDER.svg';
import shelfLife from './SHELF_LIFE.svg';
import supplier from './SUPPLIER.svg';
import timeSheet from './TIMESHEET.svg';
import totalCustomer from './TOTAL_CUSTOMERS.svg';
import totalOrders from './TOTAL_ORDERS.svg';
import units from './UNITS.svg';
import update from './UPDATE.svg';
import wastage from './WASTAGE.svg';

export const accounts_icon = accounts;
export const add_icon = add;
export const address_icon = address;
export const captain_icon = captain;
export const bill_amount_icon = billAmount;
export const ascending_icon = ascending;
export const category_icon = category;
export const chef_icon = chef;
export const cogs_icon = cogs;
export const comments_icon = comments;
export const contact_icon = contact;
export const dashboard_icon = dashboard;
export const descending_icon = descending;
export const dine_time_icon = dineTime;
export const edit_icon = edit;
export const expense_icon = expense;
export const food_surplus_icon = food_surplus;
export const fridge_icon = fridge;
export const guest_icon = guest;
export const handBurger_icon = handBurger;
export const heart_icon = heart;
export const inventoryItems_icon = inventoryItems;
export const key_icon = key;
export const lock_icon = lock;
export const measurement_icon = measurement;
export const menuItems_icon = menuItems;
export const mop_icon = mop;
export const mail_icon = mail;
export const name_icon = name;
export const order_icon = order;
export const price_icon = price;
export const quantityPerTable_icon = quantityPerTable;
export const quotation_icon = quotation;
export const rating_icon = rating;
export const rating2_icon = rating2;
export const rating3_icon = rating3;
export const remove_icon = remove;
export const restaurant_icon = restaurantIcon;
export const revenue_icon = revenue;
export const send_icon = sendIcon;
export const sendOrder_icon = sendOrder;
export const shelfLife_icon = shelfLife;
export const supplier_icon = supplier;
export const timeSheet_icon = timeSheet;
export const totalCustomer_icon = totalCustomer;
export const totalOrders_icon = totalOrders;
export const units_icon = units;
export const update_icon = update;
export const wastage_icon = wastage;



